CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE TABLE "BillPayments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Provider" character varying(100) NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "AccountType" character varying(20) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CancelledAt" timestamp with time zone,
        CONSTRAINT "PK_BillPayments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE TABLE "EmailVerifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "VerificationCode" character varying(10) NOT NULL,
        "IsVerified" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "VerifiedAt" timestamp with time zone,
        "ExpiresAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EmailVerifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE TABLE "LoginOtps" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "OtpCode" character varying(10) NOT NULL,
        "IsUsed" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_LoginOtps" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE TABLE "OperationLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Type" character varying(20) NOT NULL,
        "SenderUserId" integer,
        "RecipientUserId" integer NOT NULL,
        "DepositMethod" character varying(20),
        "Amount" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_OperationLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE TABLE "Operations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Type" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "SenderUserId" integer,
        "RecipientUserId" integer,
        "DepositMethod" character varying(20),
        "Amount" numeric NOT NULL,
        "SenderFullName" text,
        "RecipientFullName" text,
        CONSTRAINT "PK_Operations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE TABLE "PendingSignUps" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(100) NOT NULL,
        "FullName" character varying(100) NOT NULL,
        "Phone" character varying(20),
        "PassportNumber" character varying(50),
        "Address" character varying(200),
        "BirthDate" timestamp with time zone,
        "PasswordHash" text NOT NULL,
        "VerificationCode" character varying(10) NOT NULL,
        "IsVerified" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "VerifiedAt" timestamp with time zone,
        CONSTRAINT "PK_PendingSignUps" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" text NOT NULL,
        "Email" text NOT NULL,
        "Phone" text,
        "PhoneNumber" text,
        "PassportNumber" text,
        "PassportId" text,
        "Address" text,
        "BirthDate" timestamp with time zone,
        "PasswordHash" text NOT NULL,
        "Role" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreditBalance" numeric NOT NULL,
        "MainBalance" numeric NOT NULL,
        "SavingsBalance" numeric NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE TABLE "BankAccounts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Type" character varying(20) NOT NULL,
        "Balance" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_BankAccounts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BankAccounts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_BankAccounts_UserId_Type" ON "BankAccounts" ("UserId", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Users_PassportNumber" ON "Users" ("PassportNumber") WHERE [PassportNumber] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Users_Phone" ON "Users" ("Phone") WHERE [Phone] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423043309_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260423043309_InitialPostgres', '10.0.4');
    END IF;
END $EF$;
COMMIT;

